import jsPDF from 'jspdf';
import { PaperAnalysis, AcademicLevel } from '../types';

export function generatePDFReport(
  paperTitle: string,
  analysis: PaperAnalysis,
  academicLevel: AcademicLevel,
  doi?: string
): void {
  const doc = new jsPDF();
  let yPosition = 20;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);

  // Helper function to add text with automatic line wrapping
  const addWrappedText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    if (isBold) {
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setFont('helvetica', 'normal');
    }
    
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      if (yPosition > 280) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    });
    yPosition += 5;
  };

  // Header
  doc.setFillColor(120, 53, 15); // amber-900
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PaperLenz Analysis Report', margin, 20);
  
  yPosition = 45;
  doc.setTextColor(0, 0, 0);

  // Paper Information
  addWrappedText('PAPER ANALYSIS REPORT', 16, true);
  addWrappedText(`Title: ${paperTitle}`, 12, true);
  addWrappedText(`Academic Level: ${academicLevel.replace('_', ' ').toUpperCase()}`, 11);
  addWrappedText(`Generated: ${new Date().toLocaleDateString()}`, 11);
  if (doi) {
    addWrappedText(`DOI: ${doi}`, 11);
  }
  yPosition += 10;

  // One-Line Summary
  addWrappedText('ONE-LINE SUMMARY', 14, true);
  addWrappedText(analysis.one_line_summary, 11);

  // Abstract Summary
  addWrappedText('ABSTRACT SUMMARY', 14, true);
  addWrappedText(analysis.abstract_summary, 11);

  // Aim of Paper
  addWrappedText('AIM OF PAPER', 14, true);
  addWrappedText(analysis.aim_of_paper, 11);

  // Methodology/Technology Used
  addWrappedText('METHODOLOGY/TECHNOLOGY USED', 14, true);
  addWrappedText(analysis.methodology_technology_used, 11);

  // Results Obtained
  addWrappedText('RESULTS OBTAINED', 14, true);
  addWrappedText(analysis.results_obtained, 11);

  // Observations
  addWrappedText('OBSERVATIONS', 14, true);
  addWrappedText(analysis.observations, 11);

  // Limitations
  addWrappedText('LIMITATIONS', 14, true);
  analysis.limitations_detailed.forEach((limitation, index) => {
    addWrappedText(`${index + 1}. ${limitation}`, 11);
  });

  // Methodology Improvements
  addWrappedText('METHODOLOGY IMPROVEMENTS', 14, true);
  analysis.methodology_improvements.forEach((improvement, index) => {
    addWrappedText(`${index + 1}. ${improvement}`, 11);
  });

  // Glossary
  if (analysis.glossary.length > 0) {
    addWrappedText('GLOSSARY', 14, true);
    analysis.glossary.forEach(({ term, definition }) => {
      addWrappedText(`${term}: ${definition}`, 11);
    });
  }

  // Quality Score
  addWrappedText('PAPER QUALITY SCORE', 14, true);
  addWrappedText(`Overall Score: ${analysis.paper_quality_score.total}/100`, 12, true);
  Object.entries(analysis.paper_quality_score).filter(([key]) => key !== 'total').forEach(([key, value]) => {
    addWrappedText(`${key.replace('_', ' ').charAt(0).toUpperCase() + key.replace('_', ' ').slice(1)}: ${value}/20`, 11);
  });

  // Section Completeness
  addWrappedText('SECTION COMPLETENESS', 14, true);
  Object.entries(analysis.section_completeness).forEach(([section, score]) => {
    addWrappedText(`${section.replace('_', ' ').charAt(0).toUpperCase() + section.replace('_', ' ').slice(1)}: ${score}/10`, 11);
  });

  // Credibility Analysis
  addWrappedText('CREDIBILITY ANALYSIS', 14, true);
  addWrappedText(`Overall Score: ${analysis.credibility_analysis.score}/100`, 12, true);
  addWrappedText(`Journal Impact: ${analysis.credibility_analysis.journal_impact}`, 11);
  if (analysis.credibility_analysis.citation_count) {
    addWrappedText(`Citation Count: ${analysis.credibility_analysis.citation_count}`, 11);
  }
  addWrappedText('Key Factors:', 11, true);
  analysis.credibility_analysis.factors.forEach((factor, index) => {
    addWrappedText(`• ${factor}`, 11);
  });

  // Citations
  addWrappedText('CITATIONS', 14, true);
  addWrappedText('APA Format:', 11, true);
  addWrappedText(analysis.citations.apa, 10);
  addWrappedText('MLA Format:', 11, true);
  addWrappedText(analysis.citations.mla, 10);
  addWrappedText('IEEE Format:', 11, true);
  addWrappedText(analysis.citations.ieee, 10);

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by PaperLenz - See Science Clearly', margin, 290);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, 290);
  }

  // Save the PDF
  const filename = `paperlenz-analysis-${paperTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`;
  doc.save(filename);
}